SET SCHEMA FN71737;

CREATE TABLE MOVIE(
--ne e dobre da ima VARCHAR kliuch
	TITLE VARCHAR(20),
	YEAR INT,
	LENGTH INT,
	INCOLOR CHAR(1),
	STUDIONAME VARCHAR(20),
	PRODUCERC# VARCHAR(10)
);

CREATE TABLE STUDIO(
	NAME VARCHAR(20),
	ADDRESS VARCHAR(50),
	PRESC# VARCHAR(10)
);

CREATE TABLE MOVIEEXEC(
	CERT# VARCHAR(10),
	NAME VARCHAR(20),
	ADDRESS VARCHAR(50),
	NETWORTH INT
);

CREATE TABLE MOVIESTAR(
	NAME VARCHAR(20),
	ADDRESS VARCHAR(50),
	BIRTHDATE DATE,
	GENDER CHAR(1)
);

CREATE TABLE STARSIN(
	MOVIETITLE VARCHAR(20),
	MOVIEYEAR INT,
	STARNAME VARCHAR(20)
);
